apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: devopshint
          image: 637423270289.dkr.ecr.ap-south-1.amazonaws.com/node:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
